# Generated by Django 4.0.3 on 2022-04-09 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5, verbose_name='Title')),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=150, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('suffix', models.CharField(max_length=15, verbose_name='Suffix')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('main_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('alternative_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_name'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=150, verbose_name='Street')),
                ('city_town', models.CharField(max_length=50, verbose_name='City / Town')),
                ('state_province', models.CharField(max_length=150, verbose_name='State / Province')),
                ('zip', models.CharField(max_length=5, verbose_name='ZIP code')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('lat', models.DecimalField(decimal_places=7, max_digits=9, null=True)),
                ('lon', models.DecimalField(decimal_places=7, max_digits=9, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='Cliente')),
            ],
        ),
    ]
