# Generated by Django 4.0.6 on 2022-07-22 19:10

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=150, verbose_name='Street')),
                ('city_town', models.CharField(max_length=50, verbose_name='City / Town')),
                ('state_province', models.CharField(max_length=150, verbose_name='State / Province')),
                ('zip', models.CharField(max_length=5, verbose_name='ZIP code')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('lat', models.DecimalField(decimal_places=7, max_digits=9, null=True)),
                ('lon', models.DecimalField(decimal_places=7, max_digits=9, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=5, null=True, verbose_name='Title')),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('main_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('alternative_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('added', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-last_name'],
            },
        ),
    ]
