# Generated by Django 4.0.3 on 2022-04-21 02:08

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_middle_name_alter_client_suffix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='alternative_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='client',
            name='main_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
