# Generated by Django 4.0.6 on 2022-07-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_client_alternative_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='type',
            field=models.CharField(choices=[('B', 'Billing Address'), ('S', 'Shipping Address')], default='B', max_length=1),
        ),
    ]
