# Generated by Django 4.0.3 on 2022-04-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_alternative_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
