# Generated by Django 4.0.6 on 2022-07-24 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_address_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='lon',
            new_name='lng',
        ),
        migrations.RemoveField(
            model_name='client',
            name='title',
        ),
        migrations.AlterField(
            model_name='address',
            name='id_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_address', to='client.client', verbose_name='Cliente'),
        ),
    ]
