# Generated by Django 4.0.6 on 2022-07-20 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_client_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='suffix',
        ),
    ]
