# Generated by Django 4.1 on 2022-08-16 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0008_alter_address_lat_alter_address_lng'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('I', 'Inbound'), ('O', 'Outbound')], default='I', max_length=1)),
                ('answered', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField()),
            ],
            options={
                'ordering': ['id', 'date_time'],
                'get_latest_by': 'date_time',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='anon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['first_name', 'last_name'], name='name_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email', 'alternative_email'], name='email_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['main_phone', 'alternative_phone'], name='phone_idx'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('email', 'alternative_email'), name='Unique Email'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('main_phone', 'alternative_phone'), name='Unique Phone'),
        ),
        migrations.AddField(
            model_name='call',
            name='id_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.AddField(
            model_name='call',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
