# Generated by Django 4.1 on 2022-08-16 20:24

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_remove_client_unique email_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='client',
            name='unique_phone',
        ),
    ]
