# Generated by Django 4.1 on 2022-09-09 02:21

import client.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_remove_client_unique_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='call',
            options={'get_latest_by': 'date_time', 'ordering': ['-date_time']},
        ),
        migrations.AlterField(
            model_name='call',
            name='id_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_data', to='client.client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='alternative_email',
            field=models.EmailField(blank=True, max_length=100, null=True, validators=[client.models.validate_email], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='alternative_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, validators=[client.models.validate_phone]),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True, validators=[client.models.validate_email], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='main_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, validators=[client.models.validate_phone]),
        ),
    ]
