# Generated by Django 4.1 on 2022-09-22 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_item_icon_item_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('days', models.IntegerField(default=0, unique=True, verbose_name='Quantity')),
            ],
            options={
                'ordering': ['days'],
            },
        ),
        migrations.AddField(
            model_name='price',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='period_price', to='inventory.period', verbose_name='Period Price'),
        ),
    ]
